### ISSUE TITLE
HI ,FileNotFoundError: pretrained/mit_b2.pth can not be found.

### ISSUE THREAD

**Issue by yuheyuan** [dangnam739/FAFS#1]
WHen i Run bash run.sh
missing the pretrained model.
I want to know where I can find it.Thank you

```TXT
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: pretrained/mit_b2.pth can not be found.

```

**Comment by dangnam739** [comment]
Thanks for your interest!
I have added the information about pretrained models in the README.

The Mix-Transfomer (MiT) pretrained models are published in [SegFormer](https://github.com/NVlabs/SegFormer).
You can download them from [google drive](https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia?usp=sharing) or [onedrive](https://connecthkuhk-my.sharepoint.com/:f:/g/personal/xieenze_connect_hku_hk/EvOn3l1WyM5JpnMQFSEO5b8B7vrHw9kDaJGII-3N9KNhrg?e=cpydzZ). Then, pretrained models are saved to `pretrained/` (you have to create this folder) and you can continue your process.

**Comment by yuheyuan** [comment]
> 



> Thanks for your interest! I have added the information about pretrained models in the README.
> 
> The Mix-Transfomer (MiT) pretrained models are published in [SegFormer](https://github.com/NVlabs/SegFormer). You can download them from [google drive](https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia?usp=sharing) or [onedrive](https://connecthkuhk-my.sharepoint.com/:f:/g/personal/xieenze_connect_hku_hk/EvOn3l1WyM5JpnMQFSEO5b8B7vrHw9kDaJGII-3N9KNhrg?e=cpydzZ). Then, pretrained models are saved to `pretrained/` (you have to create this folder) and you can continue your process.

yes, thank you for your reply , I download the pretrained model. Stat step 1.
in your paper, your first step said very quickly.
```txt
WORK_DIR: /media/ailab/data/yy/FAFS/code/results/gtav2cityscapes//source_only
resume from epoch 0 iter 0
Start training!
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
eta: 23h 52min, epoch: 1, iter: 100, time: 1.725 s/iter, lr: 1.00e-04, loss: 1.221312
eta: 23h 54min, epoch: 1, iter: 200, time: 1.730 s/iter, lr: 1.00e-04, loss: 0.659513
eta: 23h 49min, epoch: 1, iter: 300, time: 1.729 s/iter, lr: 1.00e-04, loss: 0.510544
eta: 23h 46min, epoch: 1, iter: 400, time: 1.728 s/iter, lr: 1.00e-04, loss: 0.458281
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0
eta: 23h 43min, epoch: 1, iter: 500, time: 1.728 s/iter, lr: 1.00e-04, loss: 0.446294
```
the time maybe one day. Is it maybe your backbone become "MiT-B2" in your code, gtav2cityscapes. source_only.yaml
```txt
 BACKBONE:
    # TYPE: "R-DL-101-C1-C5-FREEZEBN"
    TYPE: "MiT-B2"
```

So I try to annotation TYPE: " MiT-B2" instead use R-DL-101-C1-C5. But it occour another problem.
```txt
  File "/home/ailab/anaconda3/envs/yy_FAFS/lib/python3.8/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: mat1 dim 1 must match mat2 dim 0
```
---------------------------------------------------------------------------------
And then I find your synthia used R-DL-101-C1-C5 backbone.
So I try change your run.sh
```txt
# source only
# python main.py --config_file config/gtav2cityscapes/source_only.yaml --work_dir ${BASE_WORK_DIR}/source_only
# become
python main.py --config_file config/synthia2cityscapes/source_only.yaml --work_dir ${BASE_WORK_DIR}/source_only
```
However, another problem occour.
```txt

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ailab/anaconda3/envs/yy_FAFS/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/media/ailab/data/yy/FAFS/code/main.py", line 73, in main_worker
    train_net(net=net, cfg=cfg, gpu=proc_idx)
  File "/media/ailab/data/yy/FAFS/code/core/workflow/trainer.py", line 238, in train_net
    loss_dict_tgt = net(t_images)
UnboundLocalError: local variable 't_images' referenced before assignment
```

**Comment by dangnam739** [comment]
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ailab/anaconda3/envs/yy_FAFS/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/media/ailab/data/yy/FAFS/code/main.py", line 73, in main_worker
    train_net(net=net, cfg=cfg, gpu=proc_idx)
  File "/media/ailab/data/yy/FAFS/code/core/workflow/trainer.py", line 238, in train_net
    loss_dict_tgt = net(t_images)
UnboundLocalError: local variable 't_images' referenced before assignment
```
About this problem, I think you can comment line 238 in `code/core/workflow/trainer.py` and try it again.
```
        else: #source only
            loss_dict = {}

            loss_dict_src = net(images, labels)
       
-->       # loss_dict_tgt = net(t_images)
            
            if entW > 0: 
                loss_dict_tgt = net(t_images)
                loss_all = loss_dict_src["loss_ce"] + entW*loss_dict_tgt["loss_ent"]  # loss of seg on src, and ent on s and t
            else:
                loss_all = loss_dict_src["loss_ce"]
                
            loss_dict.update({"loss_all": loss_all})
```
Because I previously added this line to test the `loss_ent` function in source_only phase but after, this was added in the "if..." code below. I'm so sorry for not commenting this line.

**Comment by yuheyuan** [comment]
> ```
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/home/ailab/anaconda3/envs/yy_FAFS/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
>     fn(i, *args)
>   File "/media/ailab/data/yy/FAFS/code/main.py", line 73, in main_worker
>     train_net(net=net, cfg=cfg, gpu=proc_idx)
>   File "/media/ailab/data/yy/FAFS/code/core/workflow/trainer.py", line 238, in train_net
>     loss_dict_tgt = net(t_images)
> UnboundLocalError: local variable 't_images' referenced before assignment
> ```
> 
> About this problem, I think you can comment line 238 in `code/core/workflow/trainer.py` and try it again.
> 
> ```
>         else: #source only
>             loss_dict = {}
> 
>             loss_dict_src = net(images, labels)
>        
> -->       # loss_dict_tgt = net(t_images)
>             
>             if entW > 0: 
>                 loss_dict_tgt = net(t_images)
>                 loss_all = loss_dict_src["loss_ce"] + entW*loss_dict_tgt["loss_ent"]  # loss of seg on src, and ent on s and t
>             else:
>                 loss_all = loss_dict_src["loss_ce"]
>                 
>             loss_dict.update({"loss_all": loss_all})
> ```
> 
> Because I previously added this line to test the `loss_ent` function in source_only phase but after, this was added in the "if..." code below. I'm so sorry for not commenting this line.

oh really thank you . I success run the first stage in synthia,use Resnet backbone, it looks more quickly
```txt
Start training!
eta: 6h 15min, epoch: 1, iter: 100, time: 2.422 s/iter, lr: 1.00e-04, loss: 1.302541

```

**Comment by yuheyuan** [comment]
> Thanks for your interest! I have added the information about pretrained models in the README.
> 
> The Mix-Transfomer (MiT) pretrained models are published in [SegFormer](https://github.com/NVlabs/SegFormer). You can download them from [google drive](https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia?usp=sharing) or [onedrive](https://connecthkuhk-my.sharepoint.com/:f:/g/personal/xieenze_connect_hku_hk/EvOn3l1WyM5JpnMQFSEO5b8B7vrHw9kDaJGII-3N9KNhrg?e=cpydzZ). Then, pretrained models are saved to `pretrained/` (you have to create this folder) and you can continue your process.

     hello, I find the bug and solve it in your code
. before,  I finish the source only, warmup step in the run.sh in syn2cityscapes.
 Then I start self-training roud1.But it occour the problem.

```txt
  File "/media/ailab/data/yy/FAFS/code/core/datasets/loader/dataset.py", line 76, in __getitem__
    img_pil=crop_img(im, self.center_crop),
Traceback (most recent call last):
  File "/media/ailab/data/yy/FAFS/code/core/datasets/loader/utils.py", line 88, in crop_img
    return im.crop(map(int, [w*(0.5-0.5/size), h*(0.5-0.5/size), w*(0.5+0.5/size), h*(0.5+0.5/size)]))
  File "/media/ailab/data/yy/FAFS/code/core/datasets/loader/dataset.py", line 76, in __getitem__
    img_pil=crop_img(im, self.center_crop),
  File "/media/ailab/data/yy/FAFS/code/core/datasets/loader/utils.py", line 88, in crop_img
    return im.crop(map(int, [w*(0.5-0.5/size), h*(0.5-0.5/size), w*(0.5+0.5/size), h*(0.5+0.5/size)]))
  File "/home/ailab/anaconda3/envs/yy_FAFS/lib/python3.8/site-packages/PIL/Image.py", line 1206, in crop
    if box[2] < box[0]:
  File "/home/ailab/anaconda3/envs/yy_FAFS/lib/python3.8/site-packages/PIL/Image.py", line 1206, in crop
    if box[2] < box[0]:
TypeError: 'map' object is not subscriptable
TypeError: 'map' object is not subscriptable
```
I track back the code int the code/datasets/loader/utils.py. Line of 76. you wrote
```txt
def crop_img(im, size):
    """
    crop image
    """
    w = im.size[0]
    h = im.size[1]

    return im.crop(
        map(int, [w * (0.5 - 0.5 / size), h * (0.5 - 0.5 / size), w * (0.5 + 0.5 / size), h * (0.5 + 0.5 / size)]))
```
the problem may occour in the return map.
So I googled and found the result.I add the list.It looks can susscee run.
```txt
def crop_img(im, size):
    """
    crop image
    """
    w = im.size[0]
    h = im.size[1]

    # return im.crop(
    #     map(int, [w * (0.5 - 0.5 / size), h * (0.5 - 0.5 / size), w * (0.5 + 0.5 / size), h * (0.5 + 0.5 / size)]))

    return im.crop(list(
        map(int, [w * (0.5 - 0.5 / size), h * (0.5 - 0.5 / size), w * (0.5 + 0.5 / size), h * (0.5 + 0.5 / size)])))

```
Another question I want to ask.
I run go through souce only ,warmup stages.
souce only end.the code sad "End! epch0 max metrics: 0.3156"
warmu end. the code sard "End! epoch0 Max metrics: 0.3373". Is it a little low. Oh maybe warmup step have 10 spochs. But the output only give me the epoch0 results.

**Comment by dangnam739** [comment]
Thank you for the fix about `map`. This problem can be with Python  and PIL versions, with my configuration (python 3.7) it works fine.

```
Oh maybe warmup step have 10 spochs. But the output only give me the epoch0 results.
```
Thank you, I didn't pay attention to this line. Because after finishing running, I also tested all checkpoints for each epoch, so I didn't notice the epoch number at the last line in log file. I fixed the code in trainer.py to update max_metrics_epoch (also same at sl_trainer.py). 
```
326                   # early stopping
327                    if mean_iu >= max_metrics:
328                        max_metrics = mean_iu
329                        max_metrics_iter_cnt = "epoch{}_{}".format(epoch+1, iter_cnt)
330                        metrics_decay_count = 0
331                        max_metrics_epoch = epoch               <------
```


```
souce only end.the code sad "End! epch0 max metrics: 0.3156"
warmu end. the code sard "End! epoch0 Max metrics: 0.3373". Is it a little low
```
If you run synthia on MiT backbone, I don't have available details for this part. The main experiments were done on the GTA5 context and the best experiment on GTA5 was applied to the synthia context. So I experimented synthia context with Resnet 101 backbone and the result is 38.14 (16 classes) and 43.85 (13 classes). I think MiT maybe not give really good results on synthia context.

**Comment by yuheyuan** [comment]
> Thank you for the fix about `map`. This problem can be with Python and PIL versions, with my configuration (python 3.7) it works fine.
> 
> ```
> Oh maybe warmup step have 10 spochs. But the output only give me the epoch0 results.
> ```
> 
> Thank you, I didn't pay attention to this line. Because after finishing running, I also tested all checkpoints for each epoch, so I didn't notice the epoch number at the last line in log file. I fixed the code in trainer.py to update max_metrics_epoch (also same at sl_trainer.py).
> 
> ```
> 326                   # early stopping
> 327                    if mean_iu >= max_metrics:
> 328                        max_metrics = mean_iu
> 329                        max_metrics_iter_cnt = "epoch{}_{}".format(epoch+1, iter_cnt)
> 330                        metrics_decay_count = 0
> 331                        max_metrics_epoch = epoch               <------
> ```
> 
> ```
> souce only end.the code sad "End! epch0 max metrics: 0.3156"
> warmu end. the code sard "End! epoch0 Max metrics: 0.3373". Is it a little low
> ```
> 
> If you run synthia on MiT backbone, I don't have available details for this part. The main experiments were done on the GTA5 context and the best experiment on GTA5 was applied to the synthia context. So I experimented synthia context with Resnet 101 backbone and the result is 38.14 (16 classes) and 43.85 (13 classes). I think MiT maybe not give really good results on synthia context.

I follow the yml run synthia.It's synthia2cityscapes/s1_1.yaml. I don't use MiT because it's a bit long.
```txt
MODEL:
  TYPE: "SL_UDA_Segmentor"
  BACKBONE:
    TYPE: "R-DL-101-C1-C5-FREEZEBN"
    PRETRAINED: True
```
Now I am running self-training 1 step. It looks ok because it's miou over 0.38. In all , thank you for reply, really.
```txt
epoch: 1, val_miou: 0.3879(0.3887), 0: 0.7920, 1: 0.3578, 2: 0.8167, 3: 0.1543, 4: 0.0029, 5: 0.3482, 6: 0.2195, 7: 0.2055, 8: 0.8107, 9: 0.0000, 10: 0.8380, 11: 0.6073, 12: 0.2342, 13: 0.8239, 14: 0.0000, 15: 0.3469, 16: 0.0000, 17: 0.2957, 18: 0.5169
```

**Comment by yuheyuan** [comment]
> Thanks for your interest! I have added the information about pretrained models in the README.
> 
> The Mix-Transfomer (MiT) pretrained models are published in [SegFormer](https://github.com/NVlabs/SegFormer). You can download them from [google drive](https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia?usp=sharing) or [onedrive](https://connecthkuhk-my.sharepoint.com/:f:/g/personal/xieenze_connect_hku_hk/EvOn3l1WyM5JpnMQFSEO5b8B7vrHw9kDaJGII-3N9KNhrg?e=cpydzZ). Then, pretrained models are saved to `pretrained/` (you have to create this folder) and you can continue your process.

Hi, in your run.sh.  after create pseudo label, you use s1_1_1536.yaml. Is it should be s1_1.yaml.
python main.py --config_file config/gtav2cityscapes/sl_1_1536.yaml --

```sh
export CUDA_VISIBLE_DEVICES=0

BASE_WORK_DIR="results/gtav2cityscapes/"

# source only
python main.py --config_file config/gtav2cityscapes/source_only.yaml --work_dir ${BASE_WORK_DIR}/source_only

# warmup (adversarial training)
python main.py --config_file config/gtav2cityscapes/warmup_at.yaml --resume_from ${BASE_WORK_DIR}/source_only/best_iter.pth --work_dir ${BASE_WORK_DIR}/warmup_at

# self-training round 1
python main.py --config_file config/gtav2cityscapes/sl_1.yaml --resume_from ${BASE_WORK_DIR}/warmup_at/last_iter.pth --pseudo_resume_from ${BASE_WORK_DIR}/warmup_at/best_iter.pth --work_dir ${BASE_WORK_DIR}/sl/sl_1

# create pseudo-label in round 1 with the same size at round 2
mv ${BASE_WORK_DIR}/sl/sl_1/pseudo/ ${BASE_WORK_DIR}/sl/sl_1/pseudo_1280/
python main.py --config_file config/gtav2cityscapes/sl_1_1536.yaml --resume_from ${BASE_WORK_DIR}/warmup_at/last_iter.pth --pseudo_resume_from ${BASE_WORK_DIR}/warmup_at/best_iter.pth --work_dir ${BASE_WORK_DIR}/sl/sl_1

# self-training round 2
python main.py --config_file config/gtav2cityscapes/sl_2.yaml --resume_from ${BASE_WORK_DIR}/sl/sl_1/last_iter.pth --pseudo_resume_from ${BASE_WORK_DIR}/sl/sl_1/epoch_5.pth --work_dir ${BASE_WORK_DIR}/sl/sl_2

# # # self-training round 3
python main.py --config_file config/gtav2cityscapes/sl_3.yaml --resume_from ${BASE_WORK_DIR}/sl/sl_2/last_iter.pth --pseudo_resume_from ${BASE_WORK_DIR}/sl/sl_2/epoch_5.pth --work_dir ${BASE_WORK_DIR}/sl/sl_3


```

**Comment by dangnam739** [comment]
```
# self-training round 1
python main.py --config_file config/gtav2cityscapes/sl_1.yaml --resume_from ${BASE_WORK_DIR}/warmup_at/last_iter.pth --pseudo_resume_from ${BASE_WORK_DIR}/warmup_at/best_iter.pth --work_dir ${BASE_WORK_DIR}/sl/sl_1

```
This is the command to run for the 1st self-training that includes generating pseudo labels and training.

```
# create pseudo-label in round 1 with the same size at round 2
mv ${BASE_WORK_DIR}/sl/sl_1/pseudo/ ${BASE_WORK_DIR}/sl/sl_1/pseudo_1280/
python main.py --config_file config/gtav2cityscapes/sl_1_1536.yaml --resume_from ${BASE_WORK_DIR}/warmup_at/last_iter.pth --pseudo_resume_from ${BASE_WORK_DIR}/warmup_at/best_iter.pth --work_dir ${BASE_WORK_DIR}/sl/sl_1
```
As I started, actually this command just run to regenerate pseudo label with 1536x768 resolution (training won't be performed because last checkpoint in sl-1 saved log from training in above command) .
I have to recreate the pseudo label again because the first and second self-training stage have different resolution (1280x640 and 1536x768). The merging pseudo-labels strategy requires the same resolution of the current and previous stage pseudo labels.

**Comment by yuheyuan** [comment]
> ```
> # self-training round 1
> python main.py --config_file config/gtav2cityscapes/sl_1.yaml --resume_from ${BASE_WORK_DIR}/warmup_at/last_iter.pth --pseudo_resume_from ${BASE_WORK_DIR}/warmup_at/best_iter.pth --work_dir ${BASE_WORK_DIR}/sl/sl_1
> ```
> 
> This is the command to run for the 1st self-training that includes generating pseudo labels and training.
> 
> ```
> # create pseudo-label in round 1 with the same size at round 2
> mv ${BASE_WORK_DIR}/sl/sl_1/pseudo/ ${BASE_WORK_DIR}/sl/sl_1/pseudo_1280/
> python main.py --config_file config/gtav2cityscapes/sl_1_1536.yaml --resume_from ${BASE_WORK_DIR}/warmup_at/last_iter.pth --pseudo_resume_from ${BASE_WORK_DIR}/warmup_at/best_iter.pth --work_dir ${BASE_WORK_DIR}/sl/sl_1
> ```
> 
> As I started, actually this command just run to regenerate pseudo label with 1536x768 resolution (training won't be performed because last checkpoint in sl-1 saved log from training in above command) . I have to recreate the pseudo label again because the first and second self-training stage have different resolution (1280x640 and 1536x768). The merging pseudo-labels strategy requires the same resolution of the current and previous stage pseudo labels.

Oh, I know. At first. I run the synthia->city.
And I don't find the s1_1_1536 in the syn2cityscapes dir so I think the s1_1_1536.yaml which you may probably want to  write s1_1 or missing the yaml. And I find it in the gtav2cityscapes. Thank you so much!
